spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/skeleton"
    username: user
    password: test